/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

/**
 *
 * @author Daniel
 */
public class panelCreditos extends javax.swing.JPanel {

    /**
     * Creates new form panelInicio
     */
    public panelCreditos() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCreditos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnAgregarCredito = new javax.swing.JButton();
        btnModificarCredito = new javax.swing.JButton();
        btnEliminarCredito = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(1200, 400));
        setMinimumSize(new java.awt.Dimension(2, 4));
        setPreferredSize(new java.awt.Dimension(600, 200));
        setLayout(new java.awt.BorderLayout());

        tablaCreditos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Teléfono", "Deuda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaCreditos);
        if (tablaCreditos.getColumnModel().getColumnCount() > 0) {
            tablaCreditos.getColumnModel().getColumn(0).setResizable(false);
            tablaCreditos.getColumnModel().getColumn(1).setResizable(false);
            tablaCreditos.getColumnModel().getColumn(2).setResizable(false);
            tablaCreditos.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        btnAgregarCredito.setText("Agregar Credito");
        btnAgregarCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCreditoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarCredito);

        btnModificarCredito.setText("Modificar Credito");
        btnModificarCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarCreditoActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarCredito);

        btnEliminarCredito.setText("Eliminar Credito");
        btnEliminarCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCreditoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarCredito);

        add(jPanel1, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCreditoActionPerformed
        // TODO add your handling code here:
        new modificarCredito();
    }//GEN-LAST:event_btnModificarCreditoActionPerformed

    private void btnEliminarCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarCreditoActionPerformed

    private void btnAgregarCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCreditoActionPerformed
        // TODO add your handling code here:
        
        new agregarCredito();
    }//GEN-LAST:event_btnAgregarCreditoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCredito;
    private javax.swing.JButton btnEliminarCredito;
    private javax.swing.JButton btnModificarCredito;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCreditos;
    // End of variables declaration//GEN-END:variables
}
