/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

/**
 *
 * @author Daniel
 */
public class panelInformes extends javax.swing.JPanel {

    /**
     * Creates new form panelInicio
     */
    public panelInformes() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        labelInformeDiario = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaInformeDiario = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        labelNoEditable = new javax.swing.JLabel();
        labelValorTotalDiario = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelInformeMensual = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaInformeMensual = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        labelNoEditable2 = new javax.swing.JLabel();
        labelValorTotalMensual = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(1200, 400));
        setMinimumSize(new java.awt.Dimension(2, 4));
        setPreferredSize(new java.awt.Dimension(600, 200));
        setLayout(new java.awt.GridLayout());

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        labelInformeDiario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInformeDiario.setText("Informe Diario");
        labelInformeDiario.setMaximumSize(new java.awt.Dimension(343, 16));
        labelInformeDiario.setMinimumSize(new java.awt.Dimension(343, 16));
        labelInformeDiario.setPreferredSize(new java.awt.Dimension(343, 16));
        jPanel2.add(labelInformeDiario);

        tablaInformeDiario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Cantidad", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaInformeDiario);
        if (tablaInformeDiario.getColumnModel().getColumnCount() > 0) {
            tablaInformeDiario.getColumnModel().getColumn(0).setResizable(false);
            tablaInformeDiario.getColumnModel().getColumn(1).setResizable(false);
            tablaInformeDiario.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel2.add(jScrollPane3);

        jPanel1.setLayout(new java.awt.GridLayout());

        labelNoEditable.setText("Valor total:");
        jPanel1.add(labelNoEditable);

        labelValorTotalDiario.setText("0.0");
        labelValorTotalDiario.setMinimumSize(new java.awt.Dimension(80, 16));
        labelValorTotalDiario.setPreferredSize(new java.awt.Dimension(76, 16));
        jPanel1.add(labelValorTotalDiario);

        jPanel2.add(jPanel1);

        add(jPanel2);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        labelInformeMensual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInformeMensual.setText("Informe Mensual");
        labelInformeMensual.setMaximumSize(new java.awt.Dimension(343, 16));
        labelInformeMensual.setMinimumSize(new java.awt.Dimension(343, 16));
        labelInformeMensual.setPreferredSize(new java.awt.Dimension(343, 16));
        jPanel3.add(labelInformeMensual);

        tablaInformeMensual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Cantidad", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tablaInformeMensual);
        if (tablaInformeMensual.getColumnModel().getColumnCount() > 0) {
            tablaInformeMensual.getColumnModel().getColumn(0).setResizable(false);
            tablaInformeMensual.getColumnModel().getColumn(1).setResizable(false);
            tablaInformeMensual.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel3.add(jScrollPane5);

        jPanel4.setLayout(new java.awt.GridLayout());

        labelNoEditable2.setText("Total:");
        jPanel4.add(labelNoEditable2);

        labelValorTotalMensual.setText("0.0");
        jPanel4.add(labelValorTotalMensual);

        jPanel3.add(jPanel4);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel labelInformeDiario;
    private javax.swing.JLabel labelInformeMensual;
    private javax.swing.JLabel labelNoEditable;
    private javax.swing.JLabel labelNoEditable2;
    private javax.swing.JLabel labelValorTotalDiario;
    private javax.swing.JLabel labelValorTotalMensual;
    private javax.swing.JTable tablaInformeDiario;
    private javax.swing.JTable tablaInformeMensual;
    // End of variables declaration//GEN-END:variables
}
