package paneles;

import java.sql.Statement;

/** 
 *
 * @author Daniel
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    
    //Conexion con = new Conexion();
    public Ventana() {
        initComponents();
        abrirCaja(); 
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        //con.conectar();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVentana = new javax.swing.JTabbedPane();
        panelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCaja = new javax.swing.JButton();
        btnInformes = new javax.swing.JButton();
        btnTransacciones = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        brtnCreditos = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnAjustes = new javax.swing.JButton();
        btnSalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setUndecorated(true);
        setResizable(false);

        panelVentana.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelVentana.setToolTipText("");
        panelVentana.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelVentana.setMaximumSize(new java.awt.Dimension(1200, 400));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("STORE HELPER");
        panelMenu.add(jLabel1);

        btnCaja.setText("CAJA");
        btnCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCajaActionPerformed(evt);
            }
        });
        panelMenu.add(btnCaja);

        btnInformes.setText("INFORMES");
        btnInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformesActionPerformed(evt);
            }
        });
        panelMenu.add(btnInformes);

        btnTransacciones.setText("TRANSACCIONES");
        btnTransacciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaccionesActionPerformed(evt);
            }
        });
        panelMenu.add(btnTransacciones);

        btnProductos.setText("PRODUCTOS");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        panelMenu.add(btnProductos);

        brtnCreditos.setText("CREDITOS");
        brtnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brtnCreditosActionPerformed(evt);
            }
        });
        panelMenu.add(brtnCreditos);

        btnClientes.setText("CLIENTES");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        panelMenu.add(btnClientes);

        btnAjustes.setText("AJUSTES");
        btnAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjustesActionPerformed(evt);
            }
        });
        panelMenu.add(btnAjustes);

        btnSalir.setText("SALIR");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        panelMenu.add(btnSalir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelVentana, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
                    .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelVentana, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    paneles.panelCaja panelCaja;            
    public String vpCaja="0";
    public void abrirCaja(){
         if(vpCaja=="0"){
        panelCaja = new paneles.panelCaja();
        panelVentana.addTab("Caja", panelCaja);
        panelVentana.setSelectedComponent(panelCaja);
        }else{
            panelVentana.setSelectedComponent(panelCaja);
        }
        vpCaja="1";
    } 
    paneles.panelProductos panelProductos;
    public String vpProductos="0";
    public void abrirProductos(){ 
        if(vpProductos=="0"){
            panelProductos = new paneles.panelProductos();
            panelVentana.addTab("Productos", panelProductos);
            panelVentana.setSelectedComponent(panelProductos);
        }else{
            panelVentana.setSelectedComponent(panelProductos);
        }
        vpProductos="1";
    }
    paneles.panelClientes panelClientes;
    public String vpClientes="0";
    public void abrirClientes(){ 
        if(vpClientes=="0"){
            panelClientes = new paneles.panelClientes();
            panelVentana.addTab("Clientes", panelClientes);
            panelVentana.setSelectedComponent(panelClientes);
        }else{
            panelVentana.setSelectedComponent(panelClientes);
        }
        vpClientes="1";
    }
    paneles.panelCreditos panelCreditos;
    public String vpCreditos="0";
    public void abrirCreditos(){ 
        if(vpCreditos=="0"){
            panelCreditos = new paneles.panelCreditos();
            panelVentana.addTab("Creditos", panelCreditos);
            panelVentana.setSelectedComponent(panelCreditos);
        }else{
            panelVentana.setSelectedComponent(panelCreditos);
        }
        vpCreditos="1";
    }
    paneles.panelInformes panelInformes;
    public String vpInformes="0";
    public void abrirInformes(){ 
        if(vpInformes=="0"){
            panelInformes = new paneles.panelInformes();
            panelVentana.addTab("Informes", panelInformes);
            panelVentana.setSelectedComponent(panelInformes);
        }else{
            panelVentana.setSelectedComponent(panelInformes);
        }
        vpInformes="1";
    }
    paneles.panelTransacciones panelTransacciones;
    public String vpTransacciones="0";
    public void abrirTransacciones(){ 
        if(vpTransacciones=="0"){
            panelTransacciones = new paneles.panelTransacciones();
            panelVentana.addTab("Transacciones", panelTransacciones);
            panelVentana.setSelectedComponent(panelTransacciones);
        }else{
            panelVentana.setSelectedComponent(panelTransacciones);
        }
        vpTransacciones="1";
    } 
    paneles.panelAjustes panelAjustes;
    public String vpAjustes="0";
    public void abrirAjustes(){ 
        if(vpInformes=="0"){
            panelAjustes = new paneles.panelAjustes();
            panelVentana.addTab("Ajustes", panelAjustes);
            panelVentana.setSelectedComponent(panelAjustes);
        }else{
            panelVentana.setSelectedComponent(panelAjustes);
        }
        vpAjustes="1";
    }
    
    
    
    
    
    
    private void btnCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCajaActionPerformed
        // TODO add your handling code here:
        abrirCaja();
    }//GEN-LAST:event_btnCajaActionPerformed
    
    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
        abrirProductos();
        
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformesActionPerformed
        // TODO add your handling code here:
        abrirInformes();
    }//GEN-LAST:event_btnInformesActionPerformed

    private void brtnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brtnCreditosActionPerformed
        // TODO add your handling code here:
        abrirCreditos();
    }//GEN-LAST:event_brtnCreditosActionPerformed

    private void btnAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjustesActionPerformed
        // TODO add your handling code here:
        abrirAjustes();
    }//GEN-LAST:event_btnAjustesActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        abrirClientes();
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnTransaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaccionesActionPerformed
        // TODO add your handling code here:
        abrirTransacciones();
    }//GEN-LAST:event_btnTransaccionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brtnCreditos;
    private javax.swing.JButton btnAjustes;
    private javax.swing.JButton btnCaja;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnInformes;
    private javax.swing.JButton btnProductos;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JButton btnTransacciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JTabbedPane panelVentana;
    // End of variables declaration//GEN-END:variables
}
