# Generated by Django 3.1.6 on 2021-02-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cantidad_actual', models.FloatField()),
                ('precio_venta', models.FloatField()),
                ('costo_promedio', models.FloatField(blank=True, null=True)),
                ('precio_compra', models.FloatField()),
            ],
        ),
    ]
