# Generated by Django 3.1.5 on 2021-01-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_compra',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
